services:
  app:
    image: ghcr.io/phd-kerger/nextbike-collector:v1.2
    container_name: nextbike-collector
    restart: unless-stopped
    volumes:
      - ./values.yaml:/app/values.yaml
      - ./output-json:/app/output-json
      - ./output-parquet:/app/output-parquet